import datetime
import json
import queue
import threading
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.callbacks.base import BaseCallbackHandler

from .config import OPENROUTER_API_KEY
from .ingestion import get_chroma_db, ingest_new_documents
import os

class StreamingCallbackHandler(BaseCallbackHandler):
    """Callback handler that captures tokens via queue for real-time streaming."""
    
    def __init__(self, token_queue):
        self.token_queue = token_queue
    
    def on_llm_new_token(self, token: str, **kwargs) -> None:
        """Called when a new token is generated by the LLM."""
        if token:
            self.token_queue.put(("token", token))
    
    def on_llm_error(self, error, **kwargs) -> None:
        """Called when an error occurs during LLM generation."""
        self.token_queue.put(("error", str(error)))
    
    def on_llm_end(self, response, **kwargs) -> None:
        """Called when LLM generation completes."""
        self.token_queue.put(("end", None))


def normalize_source(raw_source):
    if not raw_source:
        return "Unknown Source"
    raw_source = raw_source.rstrip("/")
    base = os.path.basename(raw_source)
    return base if base else raw_source

def get_llm():
    return ChatOpenAI(
        model="openrouter/auto",
        api_key=OPENROUTER_API_KEY,
        base_url="https://openrouter.ai/api/v1",
        temperature=0.0
    )

def setup_rag_chain():
    db = get_chroma_db()
    # Retrieve top 5 most relevant chunks
    retriever = db.as_retriever(search_kwargs={"k": 5})
    
    llm = get_llm()
    
    system_prompt = (
        "You are a helpful and accurate assistant for answering questions based on the provided documents. "
        "Use the following pieces of retrieved context to answer the user's question. "
        "If the answer cannot be found in the context, say that you don't know or cannot answer based on the provided sources. "
        "Keep the answer clear, concise, and professional.\n\n"
        "Context:\n{context}"
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])

    # LCEL chain: retrieve -> format docs -> prompt -> LLM -> parse output
    def format_docs(docs):
        return "\n\n".join(doc.page_content for doc in docs)
    
    rag_chain = (
        {"context": retriever | format_docs, "input": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )
    
    return rag_chain

def query_rag(query_text, first_query=False):
    """
    Executes a RAG query.
    If first_query is True, it triggers a check against GCS for new documents.
    Returns:
        answer (str): The generated answer from the LLM.
        sources (list): A list of unique source document names used for the answer.
        timestamp (str): The formatted timestamp when the answer was generated.
    """
    if first_query:
        print("First query of the session, checking for new documents in GCS...")
        ingest_new_documents()
        
    db = get_chroma_db()
    retriever = db.as_retriever(search_kwargs={"k": 2})
    
    # Retrieve documents for sources
    source_docs = retriever.invoke(query_text)
    # sources = set([doc.metadata.get("source", "Unknown Source") for doc in source_docs])
    sources = {
    normalize_source(doc.metadata.get("source", "Unknown Source"))
    for doc in source_docs
    }
    
    # Format context
    context = "\n\n".join(doc.page_content for doc in source_docs)
    
    llm = get_llm()
    
    system_prompt = (
        "You are a helpful and accurate assistant for answering questions based on the provided documents. "
        "Use the following pieces of retrieved context to answer the user's question. "
        "If the answer cannot be found in the context, say that you don't know or cannot answer based on the provided sources. "
        "Keep the answer clear, concise, and professional.\n\n"
        "Context:\n{context}"
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])

    # LCEL chain for answering
    chain = prompt | llm | StrOutputParser()
    answer = chain.invoke({"context": context, "input": query_text})
    
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    return answer, list(sources), timestamp


def stream_rag(query_text, first_query=False):
    """Stream the answer from the LLM token by token using callbacks for immediate token delivery."""
    if first_query:
        print("First query of the session, checking for new documents in GCS...")
        ingest_new_documents()

    db = get_chroma_db()
    retriever = db.as_retriever(search_kwargs={"k": 2})

    source_docs = retriever.invoke(query_text)
    sources = {
        normalize_source(doc.metadata.get("source", "Unknown Source"))
        for doc in source_docs
    }

    context = "\n\n".join(doc.page_content for doc in source_docs)

    llm = get_llm()

    system_prompt = (
        "You are a helpful and accurate assistant for answering questions based on the provided documents. "
        "Use the following pieces of retrieved context to answer the user's question. "
        "If the answer cannot be found in the context, say that you don't know or cannot answer based on the provided sources. "
        "Keep the answer clear, concise, and professional.\n\n"
        "Context:\n{context}"
    )

    system_message = SystemMessage(content=system_prompt.format(context=context))
    human_message = HumanMessage(content=query_text)

    # Create queue and callback for real-time token streaming
    token_queue = queue.Queue()
    callback_handler = StreamingCallbackHandler(token_queue)

    # Run LLM generation in a background thread
    def generate_in_thread():
        try:
            # Use stream() to trigger token callbacks, not invoke()
            for chunk in llm.stream(
                [system_message, human_message],
                config={"callbacks": [callback_handler]}
            ):
                # Tokens are being captured via callback handler
                pass
        except Exception as e:
            token_queue.put(("error", str(e)))

    thread = threading.Thread(target=generate_in_thread, daemon=True)
    thread.start()

    # Yield tokens as they arrive from the queue
    while True:
        try:
            msg_type, content = token_queue.get(timeout=60)
            
            if msg_type == "token":
                yield json.dumps({"type": "token", "text": content}) + "\n"
            
            elif msg_type == "error":
                yield json.dumps({"type": "error", "message": content}) + "\n"
                break
            
            elif msg_type == "end":
                # Emit finalization event with sources/timestamp
                timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                yield json.dumps({"type": "done", "sources": list(sources), "timestamp": timestamp}) + "\n"
                break
        
        except queue.Empty:
            # Timeout: LLM took too long
            yield json.dumps({"type": "error", "message": "LLM generation timeout"}) + "\n"
            break
    
    # Ensure thread completes
    thread.join(timeout=5)

