import datetime
import json
import queue
import threading
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.callbacks.base import BaseCallbackHandler

from .config import OPENROUTER_API_KEY
from .ingestion import get_chroma_db, ingest_new_documents
from .gcs_manager import get_gcs_url
import os

class StreamingCallbackHandler(BaseCallbackHandler):
    """Callback handler that captures tokens via queue for real-time streaming."""
    
    def __init__(self, token_queue):
        self.token_queue = token_queue
    
    def on_llm_new_token(self, token: str, **kwargs) -> None:
        """Called when a new token is generated by the LLM."""
        if token:
            self.token_queue.put(("token", token))
    
    def on_llm_error(self, error, **kwargs) -> None:
        """Called when an error occurs during LLM generation."""
        self.token_queue.put(("error", str(error)))
    
    def on_llm_end(self, response, **kwargs) -> None:
        """Called when LLM generation completes."""
        self.token_queue.put(("end", None))


def get_ui_sources(source_docs):
    unique_sources = {}
    for doc in source_docs:
        raw_source = doc.metadata.get("source", "")
        page = doc.metadata.get("page", None)
        
        if not raw_source:
             continue
             
        # Unique identifier for the source item
        key = f"{raw_source}_{page}"
        if key not in unique_sources:
            base_name = os.path.basename(raw_source.rstrip("/")) or raw_source
            display_name = f"{base_name} [{page}]" if page else base_name
            url = get_gcs_url(raw_source, page=page)
            unique_sources[key] = {
                "name": display_name,
                "url": url
            }
            
    return list(unique_sources.values())

def get_llm():
    return ChatOpenAI(
        model="openrouter/auto",
        api_key=OPENROUTER_API_KEY,
        base_url="https://openrouter.ai/api/v1",
        temperature=0.0
    )

def setup_rag_chain():
    db = get_chroma_db()
    # Retrieve top 5 most relevant chunks
    retriever = db.as_retriever(search_kwargs={"k": 5})
    
    llm = get_llm()
    
    system_prompt = (
        "You are a helpful and accurate assistant for answering questions based on the provided documents. "
        "Use the following pieces of retrieved context to answer the user's question. "
        "If the answer cannot be found in the context, say that you don't know or cannot answer based on the provided sources. "
        "Keep the answer clear, concise, and professional.\n\n"
        "Context:\n{context}"
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])

    # LCEL chain: retrieve -> format docs -> prompt -> LLM -> parse output
    def format_docs(docs):
        return "\n\n".join(doc.page_content for doc in docs)
    
    rag_chain = (
        {"context": retriever | format_docs, "input": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )
    
    return rag_chain

def query_rag(query_text, first_query=False):
    """
    Executes a RAG query.
    If first_query is True, it triggers a check against GCS for new documents.
    Returns:
        answer (str): The generated answer from the LLM.
        sources (list): A list of unique source document names used for the answer.
        timestamp (str): The formatted timestamp when the answer was generated.
    Raises:
        Exception: If any error occurs during query execution.
    """
    try:
        if first_query:
            print("First query of the session, checking for new documents in GCS...")
            try:
                ingest_new_documents()
            except Exception as e:
                print(f"Warning: Document ingestion failed: {e}")
                # Continue with query even if ingestion fails
        
        db = get_chroma_db()
        
        # Retrieve docs with distance scores (Chroma returns L2 distance by default, smaller is more similar)
        docs_and_scores = db.similarity_search_with_score(query_text, k=2)
        
        best_distance = min([score for doc, score in docs_and_scores]) if docs_and_scores else float('inf')
        
        # If the closest document has a distance > 1.2, consider it irrelevant
        if best_distance > 1.2:
            timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            return "I am a HR Policy Chatbot, please ask relevant question regarding policies", [], timestamp
        
        source_docs = [doc for doc, score in docs_and_scores]
        sources = get_ui_sources(source_docs)
        
        # Format context
        context = "\n\n".join(doc.page_content for doc in source_docs)
        
        llm = get_llm()
        
        system_prompt = (
            "You are a helpful and accurate assistant for answering questions based on the provided documents. "
            "Use the following pieces of retrieved context to answer the user's question. "
            "If the answer cannot be found in the context, say that you don't know or cannot answer based on the provided sources. "
            "Keep the answer clear, concise, and professional.\n\n"
            "Context:\n{context}"
        )

        prompt = ChatPromptTemplate.from_messages([
            ("system", system_prompt),
            ("human", "{input}"),
        ])

        # LCEL chain for answering
        chain = prompt | llm | StrOutputParser()
        answer = chain.invoke({"context": context, "input": query_text})
        
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        return answer, sources, timestamp
    
    except Exception as e:
        print(f"Error in query_rag: {e}")
        raise


def stream_rag(query_text, first_query=False):
    """Stream the answer from the LLM token by token using callbacks for immediate token delivery."""
    token_queue = queue.Queue()
    
    def stream_generator():
        try:
            if first_query:
                print("First query of the session, checking for new documents in GCS...")
                try:
                    ingest_new_documents()
                except Exception as e:
                    print(f"Warning: Document ingestion failed: {e}")
                    # Continue with query even if ingestion fails

            db = get_chroma_db()
            
            # Retrieve docs with distance scores
            docs_and_scores = db.similarity_search_with_score(query_text, k=2)
            
            best_distance = min([score for doc, score in docs_and_scores]) if docs_and_scores else float('inf')
            
            # If the closest document has a distance > 1.2, consider it irrelevant
            if best_distance > 1.2:
                irrelevant_message = "I am a HR Policy Chatbot, please ask relevant question regarding policies"
                yield json.dumps({"type": "token", "text": irrelevant_message}) + "\n"
                timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                yield json.dumps({"type": "done", "sources": [], "timestamp": timestamp}) + "\n"
                return

            source_docs = [doc for doc, score in docs_and_scores]
            sources = get_ui_sources(source_docs)

            context = "\n\n".join(doc.page_content for doc in source_docs)

            llm = get_llm()

            system_prompt = (
                "You are a helpful and accurate assistant for answering questions based on the provided documents. "
                "Use the following pieces of retrieved context to answer the user's question. "
                "If the answer cannot be found in the context, say that you don't know or cannot answer based on the provided sources. "
                "Keep the answer clear, concise, and professional.\n\n"
                "Context:\n{context}"
            )

            system_message = SystemMessage(content=system_prompt.format(context=context))
            human_message = HumanMessage(content=query_text)

            # Create callback for real-time token streaming
            callback_handler = StreamingCallbackHandler(token_queue)

            # Run LLM generation in a background thread
            def generate_in_thread():
                try:
                    # Use stream() to trigger token callbacks, not invoke()
                    for chunk in llm.stream(
                        [system_message, human_message],
                        config={"callbacks": [callback_handler]}
                    ):
                        # Tokens are being captured via callback handler
                        pass
                except Exception as e:
                    print(f"Error in LLM stream: {e}")
                    token_queue.put(("error", str(e)))

            thread = threading.Thread(target=generate_in_thread, daemon=True)
            thread.start()

            # Yield tokens as they arrive from the queue
            while True:
                try:
                    msg_type, content = token_queue.get(timeout=60)
                    
                    if msg_type == "token":
                        yield json.dumps({"type": "token", "text": content}) + "\n"
                    
                    elif msg_type == "error":
                        # Log full error for debugging, but send generic message to frontend
                        print(f"LLM Error (masked from user): {content}")
                        yield json.dumps({"type": "error", "message": "Service error occurred"}) + "\n"
                        break
                    
                    elif msg_type == "end":
                        # Emit finalization event with sources/timestamp
                        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        yield json.dumps({"type": "done", "sources": sources, "timestamp": timestamp}) + "\n"
                        break
                
                except queue.Empty:
                    # Timeout: LLM took too long
                    print("Error: LLM generation timeout")
                    yield json.dumps({"type": "error", "message": "Service error occurred"}) + "\n"
                    break
            
            # Ensure thread completes
            thread.join(timeout=5)
        
        except Exception as e:
            # Log full error for debugging, but send generic message to frontend
            print(f"Stream RAG error (masked from user): {e}")
            yield json.dumps({"type": "error", "message": "Service error occurred"}) + "\n"
    
    return stream_generator()

